---
- hosts: localhost
  connection: local
  become: yes

  vars:
    packer_version: 1.1.1
    docker_compose_version: 1.16.1
    ubuntu_version: xenial

  tasks:

    - name: Prefer IPv4
      lineinfile:
        dest: /etc/gai.conf
        state: present
        line: 'precedence ::ffff:0:0/96  100'
        insertafter: '^#precedence ::ffff:0:0/96  100'

    - name: Remove packages
      apt: name={{ item }} state=absent update_cache=no
      with_items:
        - libreoffice-common
        - vlc
        - thunderbird
        - gimp*
        - pidgin*
        - rhythmbox*
        - xfburn
        - xplayer*

    - name: Install packages
      apt: name={{ item }} state=present update_cache=no
      with_items:
        - apt-transport-https
        - build-essential
        - ca-certificates
        - curl
        - dnsutils
        - fonts-inconsolata
        - git
        - i3-wm
        - i3status
        - iproute2
        - iputils-ping
        - jq
        - locales
        - openssh-client
        - openssh-server
        - pv
        - python-dev
        - python-pip
        - python-setuptools
        - screenfetch
        - shellcheck
        - software-properties-common
        - sshpass
        - suckless-tools
        - sudo
        - terminator
        - tmux
        - tmuxinator
        - tzdata
        - vim
        - xfonts-terminus
        - zsh
      register: packages

    - name: Update font cache
      command: fc-cache -fv
      when: packages.changed

    - name: Add Docker CE apt key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

    - name: Add Docker CE repo
      apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable' state=present

    - name: Install Docker CE
      apt: name=docker-ce state=present update_cache=yes

    - name: Install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0775

    - name: Install packer
      unarchive:
        src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
        dest: /usr/local/bin
        mode: 0775
        copy: no
        creates: /usr/local/bin/packer

    - name: Upgrade pip
      pip: name=pip state=latest

    - name: Install virtualenv
      pip: name=virtualenv state=latest

    - name: Install boto
      pip: name=boto state=latest

    - name: Install awscli
      pip: name=awscli state=latest

    - name: sudo nopasswd
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo\s'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'

